name: 'Deploy updated BPMNs to Zeebe'

on:
  push:
    branches:
      - saas
    paths:
      - 'src/main/resources/*.bpmn' # match '*.bpmn' files (created or updated)
      - 'src/main/resources/*.dmn' # match '*.dmn' files (created or updated)
      - 'src/main/resources/*.form' # match '*.form' files (created or updated)

jobs:
  prepare-files:
    runs-on: ubuntu-latest
    outputs:
      matrix-modified: ${{ steps.file-changes.outputs.files }}
    steps:
      - name: Select added and changed resources to deploy
        uses: yumemi-inc/changed-files@v3
        id: file-changes
        with:
          statuses: added|modified
          format: 'json'
          patterns: |
            src/main/resources/*.{bpmn,dmn,form}

  get-bearer-token:
    if: ${{ needs.prepare-files.outputs.matrix-modified != '[]' }}
    needs: prepare-files
    runs-on: ubuntu-latest
    outputs:
      token: $${{ steps.get-bearer-token.outputs.token }}
    steps:
     - name: Get Bearer Token
       id: get-bearer-token
       run: |
         token=$(curl -s "https://login.cloud.camunda.io/oauth/token" --header 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'grant_type=client_credentials' --data-urlencode "client_id=${{ secrets.ZEEBE_CLIENT_ID}}" --data-urlencode "client_secret=${{ secrets.ZEEBE_CLIENT_SECRET }}" --data-urlencode 'audience=zeebe.camunda.io' | jq -r '.access_token')
         echo "token=$token" >> $GITHUB_OUTPUT

  deploy-modified-files:
    if: ${{ needs.prepare-files.outputs.matrix-modified != '[]' }}
    needs: [prepare-files, get-bearer-token]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:  ${{ fromJSON(needs.prepare-files.outputs.matrix-modified) }}
    steps:
      - name: Check Out Reference File
        uses: Bhacaz/checkout-files@v2
        with:
          files: ${{ matrix.file }}

      - name: Echo file
        run: |
          echo ${{ matrix.file }} # to test if the correct file was passed
      
      - name: Deploy to Zeebe
        id: deploy-to-zeebe
        run: |
          response=$(curl  -s -X POST "https://${{ secrets.CLUSTER_REGION }}.zeebe.camunda.io/${{ secrets.CLUSTER_ID }}/v2/deployments" -H "Authorization: Bearer ${{ needs.get-bearer-token.outputs.token }}" -F "resources=@${{ github.workspace }}/${{ matrix.file }}")
          echo "$response"
          echo "response=$response" >> $GITHUB_OUTPUT

      - name: Fail if not Deployed
        if: !contains(steps.deploy-to-zeebe.outputs.response, 'deploy')
        run: |
          exit 1